options:
  puppet-version:
    type: int
    default: 4
    description: |
      Puppet version choices are `3` or `4`.
  pin-puppet:
    type: string
    default: ''
    description: |
      Explicit version of puppet to install.
      This will override the system default for the
      general version of puppet specified by the 
      puppet-version config parameter.
  environment:
    type: string
    default: production
    description: |
      Puppet environment.
  puppet-server:
    type: string
    default: puppetmaster.test.test
    description: |
      Puppetmaster fqdn.
  ca-server:
    type: string
    default: ''
    description: |
      Puppet ca-server fqdn.
  auto-start:
    type: boolean
    default: 'true'
    description: |
      Set puppet agent auto-start, defaults to true.

